# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 994d6fd6b199ed9028af1d81e7f69db218b37b7e472c500ddf60b7ff827c30aac70065cb10e7a0d99d63d48101be181bbc8a0e483ead7b317da137cd6f99d8e9

test:
  secret_key_base: 17b2d18e05a45f12a189742b9b87868167852dfbad37867fa839e5284cf5919a1154ff142ae79f6357d93d9963e5589b2fc51844f24ac84d35007a9f2348464e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
